name: Build evtapp.netlify.app

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Read Node.js version from .node-version
        run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_OUTPUT
        id: node-version

      - name: Setup PNPM
        uses: pnpm/action-setup@v6

      - name: Use Node.js ${{ steps.node-version.outputs.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies 🔧
        run: pnpm install --frozen-lockfile

      - name: Build 🏭
        run: |
          pnpm build
          VERSION="$(date -u +'%y.%m').$(git rev-parse --short=7 HEAD)"
          sed -i "s/__APP_VERSION__/${VERSION}/g" dist/index.html dist/unrestricted/index.html
          sed -i "s/example/schoolWeb/" dist/settings.example.js
          sed -i "s/eventotest.api/eventoapp-test.apps.be.ch/" dist/settings.example.js
          mv  dist/settings.example.js  dist/settings.js
          sleep 60

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          folder: dist
          target-folder: test
