name: Lint & Test

on: [push, pull_request]

env:
  DISABLE_SERVICE_WORKER: "true"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies 🔧
        run: npm ci

      - name: Lint 🔍
        run: npm run lint

      - name: Cypress 🔬
        uses: cypress-io/github-action@v7
        with:
          build: npm run build
          start: npx http-server dist/ -p 3000 -s
          wait-on: http://localhost:3000
          config: baseUrl=http://localhost:3000
