name: Lint & Test

on: [push, pull_request]

env:
  DISABLE_SERVICE_WORKER: "true"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Read Node.js version from .node-version
        run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_OUTPUT
        id: node-version

      - name: Setup PNPM
        uses: pnpm/action-setup@v6

      - name: Use Node.js ${{ steps.node-version.outputs.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies 🔧
        run: pnpm install --frozen-lockfile

      - name: Lint 🔍
        run: pnpm lint

      - name: Cypress 🔬
        uses: cypress-io/github-action@v7
        with:
          build: pnpm build
          start: npx http-server dist/ -p 3000 -s
          wait-on: http://localhost:3000
          config: baseUrl=http://localhost:3000
