name: Build & ZIP

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies 🔧
        run: npm ci

      - name: Build and create ZIP 🏭
        run: |
          npm run build
          mv dist evento-portal
          mkdir dist
          mv evento-portal dist
          cd dist && zip --recurse-paths evento-portal.zip *
          rm -rf evento-portal

      - name: Deploy ZIP 🚀
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          folder: dist
